services:
  database:
    image: 'postgres:latest'
    ports:
    - '5432:5432'
    environment:
    - 'POSTGRES_USER=postgres'
    - 'POSTGRES_DB=magiccrystals'
    - 'POSTGRES_PASSWORD=postgres'
    volumes:
    - './volumes/kirila/postgres:/var/lib/postgresql/data'